# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ff6022d4378b5192ad0b33f756a9306a5f55d546407f4cfbbff5c1b58c809a9596b43a6c0b4f3fbdd798ebf67b3232b84f8536865513dab2fa9fbeff143d88

test:
  secret_key_base: eaed7b723dd5e91ac997af6eb4ad4746e08fadb9d9199d35f7384e3579dbd00e8ae98f539787d136531a19125771128b580713c85e56f3c8764fec2b50f0d10d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
